version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    restart: unless-stopped
    environment:
      REACT_APP_BASE_URL: 'http://localhost:3009/'
      REACT_APP_EXPIRE_COOKIE: 1
